name: compile-and-build-client
on:
  push:
    branches: [ branch_name ]

jobs:

  compile-client-windows:
    runs-on: ubuntu-20.04
    container: sdggames/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Make directories
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p build/windows
          mkdir -v -p .godot/editor
          mkdir -v -p .godot/imported

      - name: Export Windows
        run: |
          godot -v --headless export-release Windows build/windows/frag-z-client.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

      - name: Get Timestamp
        run: date > build/windows

      - name: Push exe to website repo
        env: 
          CI_COMMIT_AUTHOR: frag-z-ci
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        if: success()
        run: |
          cd lib
          git config --global user.email "username@users.noreply.github.com"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global credential.helper cache
          git clone https://${{secrets.ACCESS_TOKEN}}@github.com/frag-z/frag-z-test-website
          cp index.js exports/ -f
          cd exports
          git add .
          git commit -m "$(date)"

  compile-client-linux:
    runs-on: ubuntu-20.04
    container: sdggames/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Make directories
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p build/linux
          mkdir -v -p .godot/editor
          mkdir -v -p .godot/imported

      - name: Export Linux
        run: |
          godot -v --headless export-release Linux build/linux/frag-z-client.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux

      - name: Get Timestamp
        run: date > build/linux

      - name: Push exe to website repo
        env: 
          CI_COMMIT_AUTHOR: frag-z-ci
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        if: success()
        run: |
          cd lib
          git config --global user.email "username@users.noreply.github.com"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global credential.helper cache
          git clone https://${{secrets.ACCESS_TOKEN}}@github.com/frag-z/frag-z-test-website
          cp index.js exports/ -f
          cd exports
          git add .
          git commit -m "$(date)"

  compile-client-macOS:
    runs-on: ubuntu-20.04
    container: sdggames/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Make directories
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mkdir -v -p build/macOS
          mkdir -v -p .godot/editor
          mkdir -v -p .godot/imported

      - name: Export MacOS
        run: |
          godot -v --headless export-release MacOS build/macOS/frag-z-client.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MacOS
          path: build/macOS

      - name: Get Timestamp
        run: date > build/macOS

      - name: Push exe to website repo
        env: 
          CI_COMMIT_AUTHOR: frag-z-ci
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        if: success()
        run: |
          cd lib
          git config --global user.email "username@users.noreply.github.com"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global credential.helper cache
          git clone https://${{secrets.ACCESS_TOKEN}}@github.com/frag-z/frag-z-test-website
          cp index.js exports/ -f
          cd exports
          git add .
          git commit -m "$(date)"
